version: '3'

services:

  #python:
    #build: ./web
    #command : python httpsserver.py hellofresh givehimthejob
    #image: python:3.6
    #environment:
    #  - DEBUG=true
    #  - PORT=8080
    #volumes:
    #  - /usr/src/app
    #links:
  #    - postgres
      #- mongodb
      #- redis
  #  ports:
    #  - "8080:8080"
  postgres:
      image: onjin/alpine-postgres:9.5
      restart: unless-stopped
      ports:
          - 5432
      environment:
          LC_ALL: C.UTF-8
          POSTGRES_USER: recipesapi
          POSTGRES_PASSWORD: recipesapi
          POSTGRES_DB: recipesapi
      tty: true

  web:
    build: ./web
    command : python httpsserver.py hellofresh givehimthejob
    environment:
      - DEBUG=true
      - PORT=5000
    #volumes:
      #- .:/usr/src/app
    links:
      - postgres
    ports:
      - "5000:5000"
    depends_on:
      - postgres
